// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3qGN3GWJ9aEPtE8UCW4iijnnfeUDr7g',
    appId: '1:420503435906:android:c90a51eb9f60dbdfe3529b',
    messagingSenderId: '420503435906',
    projectId: 'teacherzone-eb4fb',
    storageBucket: 'teacherzone-eb4fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Ie3gefIqosQM6Iya7TDO8MzvqTi9CdA',
    appId: '1:420503435906:ios:5d952a1a0a019fc2e3529b',
    messagingSenderId: '420503435906',
    projectId: 'teacherzone-eb4fb',
    storageBucket: 'teacherzone-eb4fb.firebasestorage.app',
    iosBundleId: 'com.example.teacherzone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLNia9UKHF-SXQSXAyMD58xp4n2Rpdpes',
    appId: '1:420503435906:web:cd1f0043aff35fb5e3529b',
    messagingSenderId: '420503435906',
    projectId: 'teacherzone-eb4fb',
    authDomain: 'teacherzone-eb4fb.firebaseapp.com',
    storageBucket: 'teacherzone-eb4fb.firebasestorage.app',
    measurementId: 'G-N3RER5KRMG',
  );
}
